###
POST http://localhost:3000/api/policies

{
  "Coverage": "Health Insurance",
  "Premium": 15000,
  "StartDate": "2024-01-01",
  "EndDate": "2024-12-31"
}

###
GET http://localhost:3000/api/policies


###
PUT http://localhost:3000/api/policies/1
Content-Type: application/json

{
  "Premium": 18000
}



###
DELETE http://localhost:3000/api/policies/1
